FROM python:3.13.0-slim AS base

RUN apt-get update && apt-get install -y \
    python3-dev

WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

