# Generated by Django 5.2.6 on 2025-09-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cruds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(through='core.SaleItem', to='cruds.product'),
        ),
    ]
