# Generated by Django 5.2.6 on 2025-10-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sale_products_saleitem_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
