# Generated by Django 5.2.6 on 2025-10-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0002_product_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales',
        ),
    ]
